FROM inff-built-be-base AS publish
WORKDIR /src
# Publish the application for production
RUN dotnet publish "InnovateFuture.Api/InnovateFuture.Api.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
# Copy published output from the publish stage
COPY --from=publish /app/publish .

ENV ASPNETCORE_URLS=http://+:5091/
ENV ASPNETCORE_ENVIRONMENT=Development

EXPOSE 5091
ENTRYPOINT ["dotnet", "InnovateFuture.Api.dll"]