FROM inff-built-be-base

RUN dotnet tool install --global dotnet-ef --version 9.0.0

# PATH for dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

WORKDIR /src
ENTRYPOINT ["dotnet", "ef", "database", "update", \
  "--project", "InnovateFuture.Infrastructure/InnovateFuture.Infrastructure.csproj", \
  "--startup-project", "InnovateFuture.Api/InnovateFuture.Api.csproj"]
